name = "muum-repo-explorer"
compatibility_date = "2026-06-03"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "muum-repo-explorer"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "REPO_BUCKET"
bucket_name = "muum-repo-explorer-repo-snapshots"
